# Generated by Django 4.2.3 on 2024-02-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENDERBC_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='establishment_year',
            field=models.IntegerField(choices=[(2024, '2024'), (2023, '2023'), (2022, '2022'), (2021, '2021'), (2020, '2020'), (2019, '2019'), (2018, '2018'), (2017, '2017'), (2016, '2016'), (2015, '2015'), (2014, '2014'), (2013, '2013'), (2012, '2012'), (2011, '2011'), (2010, '2010'), (2009, '2009'), (2008, '2008'), (2007, '2007'), (2006, '2006'), (2005, '2005')], default=2024, verbose_name='Establishment Year'),
        ),
    ]
