# Generated by Django 4.2.3 on 2024-02-27 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENDERBC_App', '0003_tender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 11, 11, 35, 749723, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tender',
            name='start_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 11, 11, 35, 749723, tzinfo=datetime.timezone.utc)),
        ),
    ]
