# Generated by Django 4.2.3 on 2024-02-27 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENDERBC_App', '0004_alter_tender_created_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 15, 29, 17, 393794, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tender',
            name='document',
            field=models.FileField(upload_to='tender documents/'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='end_date_time',
            field=models.DateTimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='start_date_time',
            field=models.DateTimeField(verbose_name='Start'),
        ),
    ]
