# Generated by Django 5.0.3 on 2024-03-18 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENDERBC_App', '0005_alter_tender_created_date_time_alter_tender_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='Status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Completed', 'Completed')], default='Inactive', max_length=9, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 8, 46, 799789, tzinfo=datetime.timezone.utc)),
        ),
    ]
