# Generated by Django 5.0.3 on 2024-03-18 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENDERBC_App', '0006_tender_status_alter_tender_created_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 10, 9, 1, 308166, tzinfo=datetime.timezone.utc)),
        ),
    ]
