# Generated by Django 5.0.3 on 2024-03-21 06:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENDERBC_App', '0007_alter_tender_created_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 21, 6, 19, 26, 955479, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='Bid documents/')),
                ('Status', models.CharField(choices=[('Submitted', 'Submitted'), ('Accpeted', 'Accepted'), ('Rejected', 'Rejected')], default='Submitted', max_length=9, verbose_name='Status')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teneder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TENDERBC_App.tender')),
            ],
        ),
    ]
