# Generated by Django 5.0.3 on 2024-03-22 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TENDERBC_App', '0010_alter_tender_created_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='teneder',
            new_name='tender',
        ),
        migrations.AlterField(
            model_name='tender',
            name='created_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 8, 31, 59, 838243, tzinfo=datetime.timezone.utc)),
        ),
    ]
