# Generated by Django 5.0.3 on 2024-03-22 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TENDERBC_App', '0012_alter_tender_created_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='created_date_time',
        ),
    ]
